### ISSUE TITLE
Blank identifiers are declared 

### ISSUE THREAD

**Issue by lafrancef** [djeik/goto#109]
And they shouldn't be, obviously.

**Comment by tsani** [comment]
I've briefly started looking into this. It appears something is wrong with short variable declarations. The code as it's written _should_ be throwing _errors_ when a blank identifier is used in a short variable declaration (which it _shouldn't_). However, it isn't. Consequently, the global identifier for blanks is being used (which has `UnknownType`) causing the simplification to blow up with `UnrepresentableType`.
