### ISSUE TITLE
Parser error on variable declarations with malformed slice type

### ISSUE THREAD

**Issue by lafrancef** [djeik/goto#14]
`parse stmt "" "var int[] x"`
Expected: Error on `int[]`, which is not a valid type.
Actual: `DeclStmt (VarDecl (VarBody ["int"] (Just (SliceType (NamedType "x"))) [] ))`
(for clarity some type constructors have been omitted)

Note: the `type_` parser correctly rejects "int[]"

**Comment by tsani** [comment]
Not a bug.

![screen shot 2016-02-17 at 8 28 07 pm](https://cloud.githubusercontent.com/assets/903787/13130822/0c88418a-d5b5-11e5-95a2-be8ab301a792.png)

Notice that the error is a semantic one, not a parse error.

It's declaring a variable called `int` with the type `[]x` which is a slice of type `x`.
