### ISSUE TITLE
Pretty-print inserts newlines in spots that trigger semicolon insertion

### ISSUE THREAD

**Issue by lafrancef** [djeik/goto#20]
With the following extremely long expression:
`[2517641676117050668][6835291727912896]struct {}(p91O0.([6463593300084288956]struct {}))...`,
the pretty-printer inserted a line-break after the identifier `p91O0`, resulting in:

```
[2517641676117050668][6835291727912896]struct {}(p91O0
    .([6463593300084288956]struct {}))...
```

When trying to parse that again, a semi is inserted after `p91O0`, which is unexpected when parsing a selector expression. Therefore, the given expression could not be parsed, pretty-printed and re-parsed.

**Comment by lafrancef** [comment]
Apart from inside expressions, this could cause problems in:
- type declarations and type literals (contain identifiers)
- return statements (a semi may be inserted after the `return` keyword).

**Comment by tsani** [comment]
The reason this happens is that the pretty-printing library we're using automatically wraps lines past a certain length. It's possible to disable/modify this behaviour. I'll see what I can do.
