### ISSUE TITLE
Blocks are thrown away.

### ISSUE THREAD

**Issue by lafrancef** [djeik/goto#21]
Currently, if we parse something like `{a; {b; {c;}}}` we'll get the same result as if we had parsed `a; b; c;`. This is not good, since we need to keep track of explicit blocks for scoping reasons.

**Comment by tsani** [comment]
The fix should be relatively straightforward. It should just involve introducing a `Block` constructor for `StatementF`. (And patching everything that does a case analysis on `StatementF` :wink: )
