### ISSUE TITLE
Semicolon handing in postfix operator chaining is completely fucked

### ISSUE THREAD

**Issue by tsani** [djeik/goto#41]

**Comment by lafrancef** [comment]
At first blush the simplest solution seems to be to treat postfix operators as terms. Right now a term is either an operand or a conversion. We could extend this definition to include the possibility of a term with no semi followed by a postfix operator.

**Comment by tsani** [comment]
That's essentially the solution that we came up with yesterday, but even better since it accounts for the possibility of parenthesizing things.

**Comment by lafrancef** [comment]
It also handles postfixes after conversions, which are allowed:

``` go
var a [10]int64
var b = [10]int64(a)[1] //OK
```

**Comment by lafrancef** [comment]
Now that this is fixed, the only "valid" programs that don't pass are those that use an invalid expression in statement context.
