### ISSUE TITLE
Prefix operator chaining is too eager.

### ISSUE THREAD

**Issue by lafrancef** [djeik/goto#45]
`parse (expr >>= unSemiP) "" "--x"`
Expected: parse error (see https://play.golang.org/p/0VswjPfZBf)
Actual: parsed as `UnaryOp Negative (UnaryOp Negative (Variable "x"))`

**Comment by tsani** [comment]
However, `-+3` is a valid expression. I think the solution is just to add `++` and `--` to the list of "forbidden operators" in the expression parser.
