### ISSUE TITLE
All expressions are valid statements

### ISSUE THREAD

**Issue by tsani** [djeik/goto#5]
The spec is that only certain kinds of expressions are valid statements.

See 9f72605

**Comment by lafrancef** [comment]
In case you were planning to change the parser to fix this, I don't know if the parser is right place. If you do for example:

``` go
package main
func main() {
  2 + 2 // Illegal expression as statement
}
```

The error you get is `2+2 evaluated but not used`. It doesn't look like a syntax error, more like a semantic error.

**Comment by tsani** [comment]
The spec grammatically allows any expression to appear as a statement; that's true. However, it mentions that "With the exception of specific built-in functions, function and method calls and receive operations can appear in statement context. Such statements may be parenthesized."

It seems then that only function calls are really allowed. If we can detect this type of error as early as during parsing, why not do it?

**Comment by lafrancef** [comment]
I don't really mind where we detect the error, but it would be nice to have an appropriate error message. However If it's simpler to do in the parser then let's do that.
