### ISSUE TITLE
Parsing chained calls: arguments are in reverse order

### ISSUE THREAD

**Issue by lafrancef** [djeik/goto#6]
```
parse (expr >>= unSemiP) "" "f(a)(b)(c)"
```

Expected:

```
Right 
(Call 
  (Call 
    (Call (Variable "f") (NormalArguments [Variable "a"])) 
  (NormalArguments [Variable "b"])) 
(NormalArguments [Variable "c"]))
```

Actual:

```
Right 
(Call 
  (Call 
    (Call (Variable "f") (NormalArguments [Variable "c"])) 
  (NormalArguments [Variable "b"])) 
(NormalArguments [Variable "a"]))
```

Only an associativity problem it seems.

**Comment by tsani** [comment]
I ran into this bug in the first version of the expression parser and patched it. Introducing semicolon processing seems to have caused a regression. The fix the first time this happened was to switch the order of the function compositions for postfix operator chaining. I'll try to put in a patch tonight.
