### ISSUE TITLE
Redeclaration analysis for short variable declaration is too strict

### ISSUE THREAD

**Issue by lafrancef** [djeik/goto#86]
The following program is valid golite but is rejected by goto:

``` go
package main

type a int

func main() {
    a := 2
    print(a)
}
```

In other words, short variable declarations only look at variables.

**Comment by tsani** [comment]
I think the problem here is that my redeclaration analysis is too strict; it doesn't account for shadowing. It would be valid to write:

```
x := 3
{
   x := 5
}
```

**Comment by lafrancef** [comment]
Correct. The following program fragment fails:

```
type a int
a := 2
```
